name: Java App CI/CD Workflow
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
permissions:
  contents: write
 
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Check out code
    - name: Checkout Code
      uses: actions/checkout@v3
 
    # Step 2: Set up Java and Maven
    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven
 
    # Step 3: Build the Java application
    - name: Build Application with Maven
      run: mvn clean package
 
    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    # Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/java-app
        IMAGE_TAG=${{ github.run_number }}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
 
   # Push the Docker image with the version tag
    - name: Push Docker image with dynamic version
      run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
          IMAGE_TAG=${{ github.run_number }}
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
